#include <iostream.h>
#include <conio.h>
main()
{
cout<<"SSSSSS     UU  UU        MMMM      MMMM";
cout<<"\nSSSSSS     UU  UU        MMMM      MMMM";
cout<<"\nSS         UU  UU        MM MM    MM MM";
cout<<"\nSS         UU  UU        MM  MM  MM  MM";
cout<<"\nSSSSSS     UU  UU        MM   MMMM   MM";
cout<<"\n    SS     UU  UU        MM          MM";
cout<<"\n    SS     UU  UU        MM          MM";
cout<<"\nSSSSSS     UUUUUU        MM          MM";
cout<<"\nSSSSSS     UUUUUU        MM          MM";
getch();
}